[changelog]
# Remove header and footer completely
header = ""
footer = ""

# Changelog body template
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}{% else %}## [Unreleased]{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ REPO_NAME }} — {{ group | upper_first }}
{%- for commit in commits %}
  {%- set msg = commit.message | split(pat="\n") | first | trim %}
  {%- set cleaned = msg | regex_replace(pat="^[a-z]+\\([\\w\\-]+\\)?:\\s*", rep="") %}
  - {{ cleaned | upper_first }}
    {%- if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}
    {%- if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }}){% endif %}
{%- endfor %}
{% endfor %}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false

commit_preprocessors = [
  # Remove issue numbers
  { pattern = "\\((\\w+\\s)?#(\\d+)\\)", replace = "" },
]

commit_parsers = [
  { message = "^release", skip = true },
  { message = "^[a|A]dd", group = "Added" },
  { message = "^[s|S]upport", group = "Added" },
  { message = "^[r|R]emove", group = "Removed" },
  { message = "^.*: add", group = "Added" },
  { message = "^.*: support", group = "Added" },
  { message = "^.*: remove", group = "Removed" },
  { message = "^.*: delete", group = "Removed" },
  { message = "^test", group = "Fixed" },
  { message = "^fix", group = "Fixed" },
  { message = "^.*: fix", group = "Fixed" },
  { message = "^.*", group = "Changed" },
]

filter_commits = false
topo_order = false
sort_commits = "newest"
