[changelog]
trim = true

body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}{% if env.REPO_NAME %} ({{ env.REPO_NAME }}){% endif %}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{%- for commit in commits %}
  - {{ commit.message | regex_replace(pat="^(\\w+)(\\(.*\\))?!?:\\s*", sub="") | split(pat="\n") | first | trim | capitalize }}\
    {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}\
    {% if commit.remote.pr_number %} in \
    [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
    {%- endif %}
{%- endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
## New Contributors
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
* @{{ contributor.username }} made their first contribution
  {%- if contributor.pr_number %} in \
    [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
  {%- endif %}
{%- endfor %}
{%- endif %}
"""

# Optional: disable footer to remove compare URLs and make output cleaner
footer = ""

[git]
conventional_commits = true
filter_unconventional = false

# Strip issue references
commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

# Classify commit types into groups
commit_parsers = [
  { message = "^[a|A]dd", group = "Added" },
  { message = "^[s|S]upport", group = "Added" },
  { message = "^[r|R]emove", group = "Removed" },
  { message = "^.*: add", group = "Added" },
  { message = "^.*: support", group = "Added" },
  { message = "^.*: remove", group = "Removed" },
  { message = "^.*: delete", group = "Removed" },
  { message = "^test", group = "Fixed" },
  { message = "^fix", group = "Fixed" },
  { message = "^.*: fix", group = "Fixed" },
  { message = "^chore\\(release\\):", skip = true },
  { message = "^Merge pull request", skip = true },
  { message = "^.*", group = "Changed" },
]

filter_commits = true
filter_merge_commits = true
topo_order = false
sort_commits = "newest"
