# -*- mode: ruby -*-
# vi: set ft=ruby :


NODE_IP = "192.168.178.106"

BOX_CPUS = 4          # should be integer, not string
BOX_RAM = 8192        # should be integer, not string


VAGRANT_DISABLE_VBOXSYMLINKCREATE = "1"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.box_version = "4.24.0529"
  config.vm.box_check_update = true
  config.ssh.forward_agent = true

  config.vm.provision "shell", inline: <<-SHELL
    # German keyboard
    loadkeys de-latin1

    # Configure locale
    sed -i '/^#en_AU.UTF-8 UTF-8/s/^#//' /etc/locale.gen
    locale-gen
    echo "LANG=en_AU.UTF-8" > /etc/locale.conf
    export LANG=en_AU.UTF-8

    # System update and host config
    pacman-key --init
    pacman-key --populate archlinux
    pacman-key --refresh-keys || true  # fallback if keyserver is unreachable
    pacman -Syyu --noconfirm --needed archlinux-keyring
    echo "" >> /etc/hosts
    echo "$NODE_IP     wks.fritz.box  wks" >> /etc/hosts
  SHELL

  config.vm.define "wks" do |wks|
    wks.vm.hostname = "wks"
    wks.vm.network "public_network", ip: NODE_IP

    wks.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "wks"
      vb.customize ["modifyvm", :id, "--groups", "/DevOps-Lab/automation"]
      vb.cpus = BOX_CPUS
      vb.memory = BOX_RAM
    end
  end
end
