# -*- mode: ruby -*-
# vi: set ft=ruby :

MASTER_SRV = "192.168.178.102"
NODE_IPS = {
  1 => "192.168.178.103",
  2 => "192.168.178.104",
  3 => "192.168.178.105"
}

VM_CPUS = 2
VM_RAM = 4096

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"
  config.vm.box_check_update = true
  config.ssh.forward_agent = true

  config.vm.provision "shell", inline: <<-SHELL
    echo "fastestmirror=True" >> /etc/dnf/dnf.conf
    echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf
    dnf makecache
    dnf -y update
    echo "" >> /etc/hosts
    echo "#{MASTER_SRV}     dev-k8s-master.fritz.box    dev-k8s-master" >> /etc/hosts
    echo "#{NODE_IPS[1]}    dev-k8s-node01.fritz.box    dev-k8s-01" >> /etc/hosts
    echo "#{NODE_IPS[1]}    dev-k8s-node02.fritz.box    dev-k8s-node02" >> /etc/hosts
    echo "#{NODE_IPS[1]}    dev-gk8s-node03.fritz.box   dev-k8s-node03" >> /etc/hosts
  SHELL

  config.vm.define "master" do |master|
    master.vm.hostname = "dev-k8s-master"
    master.vm.network "public_network", ip: MASTER_SRV

    master.vm.define "virtualbox" do |vb|
      vb.gui = false
      vb.name = "dev-k8s-master"
      vb.customize ["modifyvm", :id, "--groups", "/DevOps-Lab/K8S"]
      vb.cpus = VM_CPUS
      vb.memory = VM_RAM
    end

  # Worker Nodes
  NODE_IPS.each do |i, ip|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "dev-k8s-node0#{i}"
      node.vm.network "public_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.name = "dev-k8s-node0#{i}"
        vb.customize ["modifyvm", :id, "--groups", "/DevOps-Lab/K8S"]
        vb.cpus = VM_CPUS
        vb.memory = VM_RAM
      end

      node.vm.provision "shell", inline: <<-SHELL
        echo "hello from node #{i}"
      SHELL
    end
  end
end
