# -*- mode: ruby -*-
# vi: set ft=ruby :

GRAF_SRV = "xxx.xxx.xxx.xxx"

BOX_CPUS = "2"
BOX_RAM = "4096"

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"
  config.vm.box_check_update = true
  config.ssh.forward_agent = true

  config.vm.provision "shell", inline: %Q{
    localectl set-keymap de-deadgraveacute
    # Configuring DNF
    echo "fastestmirror=True" >> /etc/dnf/dnf.conf
    echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf
    dnf makecache
    dnf -y update
  }

  config.vm.define "grafana" do |grafana|
    grafana.vm.hostname = "grafana01"
    grafana.vm.network "public_network", ip: GRAF_SRV
    grafana.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "grafana01"
      vb.customize ["modifyvm", :id, "--groups", "/DevOps-Lab/Monitoring"]
      vb.customize ["modifyvm", :id, "--memory", BOX_RAM]
      vb.customize ["modifyvm", :id, "--cpus", BOX_CPUS]
    end
  end
end
