---
name: Generate Changelog on Tag

on:
  "push":
    tags:
      - 'v*'

permissions:
  contents: "write"

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git-cliff
        run: |
          VERSION="2.9.1"
          ARCH="x86_64-unknown-linux-gnu"
          ARCHIVE="git-cliff-${VERSION}-${ARCH}.tar.gz"
          GIT_CLIFF_URL="https://github.com/orhun/git-cliff/releases/download/v${VERSION}/${ARCHIVE}"
          curl -sSL "GIT_CLIFF_URL" -o git-cliff
          tar -xf git-cliff
          sudo mv git-cliff-"${VERSION}"/git-cliff /usr/local/bin
          sudo chmod +x /usr/local/bin/git-cliff
      
      - name: Generate changelog
        run: |
          git-cliff --config .git-cliff.toml -o CHANGELOG.md
      
      - name: Commit and push changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          if ! git diff --cached --quiet; then
            git commit -m "docs(changelog): update for ${{ github.ref_name }}"
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
